url: http://www.growandblossompreschool.com
baseurl: 

# Site settings
title: Grow and Blossom PreSchool Center
email: info@growandblossompreschool.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

about: "<p>Welcome to Grow and Blossom Preschool Center!
<p>The following information is intended to inform and guide you as we work together to provide the very best child care experience and developmental opportunities for your child(ren). We are dedicated to working with you and recognize the central importance of communication to our success. We encourage questions and comments. We invite compliments and criticisms. All doors are open to you at all times; please visit when convenient, volunteer whenever possible and stay in touch with us.</p>
<p>Grow and Blossom Preschool center serves children from 2 and a half years to 12 years of age in developmentally appropriate spaces in classrooms as well as offering plentiful outdoor play areas. Our daily interactions and activities are based on age-appropriate developmental expectations and individual goals established for each child in conjunction with the family.</p>"

mission: "<p>Grow and Blossom Preschool Center’s mission is to provide high quality educational services using a developmentally appropriate preschool curriculum for a multi-economic and culturally diverse group of young children.</p>
<p>​To achieve our mission, the following objectives provide the foundation for which our goals can be met.</p>
<ul>
    <li>To maintain a student body and staff that reflects the diversity of the greater Washington Metropolitan area.</li>
    <li> To maintain and support cultural and linguistic diversity for the student body and the staff</li>
    <li>To provide a high quality, developmentally appropriate, early childhood program.</li>
    <li>To provide a curriculum, which is appropriate for young children and is consistent with the way young children learn</li>
    <li>To provide a clean, safe, stimulating, and secure environment, that allows and encourages children’s individuality and creativity</li>
    <li>To set up a learning environment that fosters growth and competence in all developmental areas</li>
    <li>To promote cultural awareness and appreciation</li>
    <li>To teach children about different cultures within the different areas of the curriculum</li>
    <li>To maintain and ethnic and cultural diverse environment at the center</li>
    <li> To establish open and beneficial relationships between parents and staff</li>
    <li>To communicate with parents about overall program as well as their child’s progress and accomplishments</li>
    <li>To encourage parents to actively participate in activities within the program</li>
</ul>"

tuition: "<p>Grow and Blossom Preschool Center's fee is for:</p>
  <ul>
    <li>Age 2.5 -4years -- $300.00 per week</li>
    <li>Age 4 -5 years -- $ 280.00 per week</li>
    <li>After School (School Age) from $150.00 per week</li>
    <li>Before School --    $ 120.00 per week</li>
  </ul>

  <p>A fee statement is prepared and delivered to you via email on the first of each month. Fees are charged on a monthly basis. Fees are due the first of each month, however parents may choose to pay in two payments, half on the first of the month and the remainder on the 15th of the month. Fees are charged and due regardless of absence due to illness or vacation.
Fee boxes located near the entrances should be used for checks or money orders. Cash payments are not accepted. Payments are due by the 5th of each month. If payment is received after the 5th, a $25 late fee will apply.</p>
  <p>Failure to pay fees is grounds for dis-enrollment.</p>
  <p>Failure to pay fees or make arrangements for payment may result in a referral to a collection service that will result in additional charges.</p>
  
  <h4>Enrollment</h4>
  <p>A completed application and $75.00 registration fee is required to begin the admissions process or place your child on a waiting list. At the time of enrollment, the first month and the last two tuition is due. The last two weeks tuition will be used if/when the parents decide to withdraw the child from Grow and Blossom Preschool Center.</p>
  <p>Enrollment will begin with an orientation to the information in this handbook, a tour and introductions to staff and teachers. Upon admissions parents are required to provide a birth certificate and an up-to-date immunization record for children. Parents will be requested to complete forms that provide contact and emergency information as well as information on their child’s unique needs, expectations and issues to address in the transition. This is intended to be the beginning of a dialogue between staff and family that continues.</p>
  
  <h4>Sibling Discount</h4>
  <p>At Grow and Blossom Preschool, we encourage families to consider sending all of their children to our center. In support of this belief we offer a sibling discount to families who have two or more siblings enrolled concurrently at the school. Families with two students at the school receive a 10% discount on one child. Families with three students at the school receive a 10% discount on the second child, and a 5% discount on the third child.</p>

  <h4>Military Discounts</h4>
  <p>Grow and Blossom Preschool Center is proud to offer a 10% Military discount on our childcare services. We are happy to serve those who serve us. Active Duty, Retirees, Veterans and Military Spouses all qualify. Discount does not apply to other services or fees. Discount offer cannot be combined with any other promotion or discount and proper military ID is required for verification. This offer does not expire and is good until further notice.</p>
"

# Team names, titles and social links
people:
- name: Janine Fetters
  pic: 5
  position: Executive Director
  email: info@growandblossompreschool.com
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

- name: Kiysha Ramey-Jenkins
  pic: 4
  position: Associate Director
  email: TMCDC@ao.uscourts.gov
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 2001 14th St, SE
  - line: Washington, DC 20020

contact:
  description: Please contact us for more information about the Center. Our staff are ready to answer any questions you may have.

  location:
    -
      name: Thurgood Marshall Federal Judiciary Building (located next to Union Station)
      address1: One Columbus Circle, NE
      city: Washington
      state: DC
      zipCode: 20544

  phone: (202) 502-2475

# Build settings
livereload: true
markdown: kramdown
permalink: pretty
