url: http://www.growandblossompreschool.com
baseurl: 

# Site settings
title: Grow and Blossom PreSchool Center
email: info@growandblossompreschool.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

about: "<p>Grow and Blossom Preschool Center’s mission is to provide high quality educational services using a developmentally appropriate preschool curriculum for a multi-economic and culturally diverse group of young children.</p>
<p>​To achieve our mission, the following objectives provide the foundation for which our goals can be met.</p>
<ul>
    <li>To maintain a student body and staff that reflects the diversity of the greater Washington Metropolitan area.</li>
    <li> To maintain and support cultural and linguistic diversity for the student body and the staff</li>
    <li>To provide a high quality, developmentally appropriate, early childhood program.</li>
    <li>To provide a curriculum, which is appropriate for young children and is consistent with the way young children learn</li>
    <li>To provide a clean, safe, stimulating, and secure environment, that allows and encourages children’s individuality and creativity</li>
    <li>To set up a learning environment that fosters growth and competence in all developmental areas</li>
    <li>To promote cultural awareness and appreciation</li>
    <li>To teach children about different cultures within the different areas of the curriculum</li>
    <li>To maintain and ethnic and cultural diverse environment at the center</li>
    <li> To establish open and beneficial relationships between parents and staff</li>
    <li>To communicate with parents about overall program as well as their child’s progress and accomplishments</li>
    <li>To encourage parents to actively participate in activities within the program</li>
</ul>"

# Team names, titles and social links
people:
- name: Janine Fetters
  pic: 5
  position: Executive Director
  email: info@growandblossompreschool.com
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

- name: Kiysha Ramey-Jenkins
  pic: 4
  position: Associate Director
  email: TMCDC@ao.uscourts.gov
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 2001 14th St, SE
  - line: Washington, DC 20020

contact:
  description: Please contact us for more information about the Center. Our staff are ready to answer any questions you may have.

  location:
    -
      name: Thurgood Marshall Federal Judiciary Building (located next to Union Station)
      address1: One Columbus Circle, NE
      city: Washington
      state: DC
      zipCode: 20544

  phone: (202) 502-2475

# Build settings
livereload: true
markdown: kramdown
permalink: pretty
